### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by sarbazvatanatan** [openai/openai-cookbook#1160]
[optional template]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/openai/openai-cookbook/pull/1103
- [ ] https://github.com/openai/openai-cookbook/issues/1158
- [x] u
- [ ] https://github.com/openai/openai-cookbook/issues/1159
- [ ] https://github.com/openai/openai-cookbook/pull/1155
- [ ] https://github.com/openai/openai-cookbook/pull/1148
```
