### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ABirHAsan123-beep** [openai/openai-cookbook#1201]
[optional template]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/openai/openai-cookbook/issues/1157
- [ ] https://github.com/openai/openai-cookbook/pull/1056
- [ ] https://github.com/openai/openai-cookbook/pull/1218
```

**Comment by ABirHAsan123-beep** [comment]
#1201
