### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by QWolfp3** [openai/openai-cookbook#1392]
[optional template]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/openai/openai-cookbook/pull/1271
- [ ] https://github.com/openai/openai-cookbook/issues/1391
- [ ] https://github.com/openai/openai-cookbook/issues/1232
- [ ] https://github.com/openai/openai-cookbook/issues/1251
- [ ] https://github.com/openai/openai-cookbook/issues/1390
- [ ] https://github.com/openai/openai-cookbook/issues/1387
- [ ] https://github.com/openai/openai-cookbook/pull/1250
- [ ] https://github.com/openai/openai-cookbook/issues/1389
- [ ] https://github.com/openai/openai-cookbook/pull/1218
- [ ] https://github.com/openai/openai-cookbook/pull/1388
- [ ] https://github.com/openai/openai-cookbook/pull/1386
- [ ] https://github.com/openai/openai-cookbook/pull/1381
- [ ] https://github.com/openai/openai-cookbook/issues/1385
- [ ] https://github.com/openai/openai-cookbook/pull/1380
- [ ] https://github.com/openai/openai-cookbook/pull/1384
- [ ] https://github.com/openai/openai-cookbook/pull/1378
- [ ] https://github.com/openai/openai-cookbook/issues/1383
- [ ] https://github.com/openai/openai-cookbook/pull/1377
- [ ] https://github.com/openai/openai-cookbook/pull/1374
- [ ] https://github.com/openai/openai-cookbook/pull/1379
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/openai/openai-cookbook/issues/1393
- [ ] https://github.com/openai/openai-cookbook/issues/1257
- [ ] https://github.com/openai/openai-cookbook/pull/1261
- [ ] https://github.com/openai/openai-cookbook/pull/1271
- [ ] https://github.com/openai/openai-cookbook/issues/1391
- [ ] https://github.com/openai/openai-cookbook/issues/1232
- [ ] https://github.com/openai/openai-cookbook/issues/1251
- [ ] https://github.com/openai/openai-cookbook/issues/1390
- [ ] https://github.com/openai/openai-cookbook/pull/1250
```

```[tasklist]
### Tasks
- [ ] https://github.com/openai/openai-cookbook/issues/1393
- [ ] https://github.com/openai/openai-cookbook/issues/1257
- [ ] https://github.com/openai/openai-cookbook/pull/1261
- [ ] https://github.com/openai/openai-cookbook/pull/1271
- [ ] https://github.com/openai/openai-cookbook/issues/1391
```

```[tasklist]
### Tasks
- [ ] https://github.com/openai/openai-cookbook/issues/1393
- [ ] https://github.com/openai/openai-cookbook/issues/1257
- [ ] https://github.com/openai/openai-cookbook/pull/1261
- [ ] https://github.com/openai/openai-cookbook/pull/1271
- [ ] https://github.com/openai/openai-cookbook/issues/1391
- [ ] https://github.com/openai/openai-cookbook/issues/1232
- [ ] https://github.com/openai/openai-cookbook/issues/1251
- [ ] https://github.com/openai/openai-cookbook/issues/1390
- [ ] https://github.com/openai/openai-cookbook/pull/1250
```

```[tasklist]
### Tasks
- [ ] https://github.com/openai/openai-cookbook/pull/1509
- [ ] https://github.com/openai/openai-cookbook/pull/1426
- [ ] https://github.com/openai/openai-cookbook/pull/1453
```

**Comment by QWolfp3** [comment]
> Hi QWolf. Is this something I need to respond to before proceeding with merging?

If you can yes ;-) Trying this for the first time so learning as I go.
